#include <ThirdParty/Vulkan/vulkan.h>

#include <Engine/Graphics_VulkanInternal.h>

const char* eng_InternalVkResultToString(VkResult result)
{
	// https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkResult.html
	switch (result)
	{
		////////////////////////////////////////////////////////////////////////// Success codes
		case VK_SUCCESS:
			return "VK_SUCCESS Command successfully completed.";
		case VK_NOT_READY:
			return "VK_NOT_READY A fence or query has not yet completed.";
		case VK_TIMEOUT:
			return "VK_TIMEOUT A wait operation has not completed in the specified time.";
		case VK_EVENT_SET:
			return "VK_EVENT_SET An event is signaled.";
		case VK_EVENT_RESET:
			return "VK_EVENT_RESET An event is unsignaled.";
		case VK_INCOMPLETE:
			return "VK_INCOMPLETE A return array was too small for the result.";

		////////////////////////////////////////////////////////////////////////// Error codes
		case VK_ERROR_OUT_OF_HOST_MEMORY:
			return "VK_ERROR_OUT_OF_HOST_MEMORY A host memory allocation has failed.";
		case VK_ERROR_OUT_OF_DEVICE_MEMORY:
			return "VK_ERROR_OUT_OF_DEVICE_MEMORY A device memory allocation has failed.";
		case VK_ERROR_INITIALIZATION_FAILED:
			return "VK_ERROR_INITIALIZATION_FAILED Initialization of an object could not be completed for implementation-specific reasons.";
		case VK_ERROR_DEVICE_LOST:
			return "VK_ERROR_DEVICE_LOST The logical or physical device has been lost. See: https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkResult.html#devsandqueues-lost-device";
		case VK_ERROR_MEMORY_MAP_FAILED:
			return "VK_ERROR_MEMORY_MAP_FAILED Mapping of a memory object has failed.";
		case VK_ERROR_LAYER_NOT_PRESENT:
			return "VK_ERROR_LAYER_NOT_PRESENT A requested layer is not present or could not be loaded.";
		case VK_ERROR_EXTENSION_NOT_PRESENT:
			return "VK_ERROR_EXTENSION_NOT_PRESENT A requested extension is not supported.";
		case VK_ERROR_FEATURE_NOT_PRESENT:
			return "VK_ERROR_FEATURE_NOT_PRESENT A requested feature is not supported.";
		case VK_ERROR_INCOMPATIBLE_DRIVER:
			return "VK_ERROR_INCOMPATIBLE_DRIVER The requested version of Vulkan is not supported by the driver or is otherwise incompatible for implementation-specific reasons.";
		case VK_ERROR_TOO_MANY_OBJECTS:
			return "VK_ERROR_TOO_MANY_OBJECTS Too many objects of the type have already been created.";
		case VK_ERROR_FORMAT_NOT_SUPPORTED:
			return "VK_ERROR_FORMAT_NOT_SUPPORTED A requested format is not supported on this device.";
		case VK_ERROR_FRAGMENTED_POOL:
			return "VK_ERROR_FRAGMENTED_POOL A requested pool allocation has failed due to fragmentation of the pool’s memory.";

		////////////////////////////////////////////////////////////////////////// Not documented by Khronos
		case VK_ERROR_SURFACE_LOST_KHR:
			return "VK_ERROR_SURFACE_LOST_KHR (documentation unavailable).";
		case VK_ERROR_NATIVE_WINDOW_IN_USE_KHR:
			return "VK_ERROR_NATIVE_WINDOW_IN_USE_KHR (documentation unavailable).";
		case VK_SUBOPTIMAL_KHR:
			return "VK_SUBOPTIMAL_KHR (documentation unavailable).";
		case VK_ERROR_OUT_OF_DATE_KHR:
			return "VK_ERROR_OUT_OF_DATE_KHR (documentation unavailable).";
		case VK_ERROR_INCOMPATIBLE_DISPLAY_KHR:
			return "VK_ERROR_INCOMPATIBLE_DISPLAY_KHR (documentation unavailable).";
		case VK_ERROR_VALIDATION_FAILED_EXT:
			return "VK_ERROR_VALIDATION_FAILED_EXT (documentation unavailable).";
		case VK_ERROR_INVALID_SHADER_NV:
			return "VK_ERROR_INVALID_SHADER_NV (documentation unavailable).";
		case VK_ERROR_OUT_OF_POOL_MEMORY_KHR:
			return "VK_ERROR_OUT_OF_POOL_MEMORY_KHR (documentation unavailable).";
		case VK_ERROR_INVALID_EXTERNAL_HANDLE_KHX:
			return "VK_ERROR_INVALID_EXTERNAL_HANDLE_KHX (documentation unavailable).";
		default:
			return "Unknown result.";
	}
}

const char* eng_InternalVKFormatToString(VkFormat format)
{
	static char* knownFormats[VK_FORMAT_RANGE_SIZE] = { "UNDEFINED", "R4G4_UNORM_PACK8", "R4G4B4A4_UNORM_PACK16", "B4G4R4A4_UNORM_PACK16", "R5G6B5_UNORM_PACK16", "B5G6R5_UNORM_PACK16", "R5G5B5A1_UNORM_PACK16", "B5G5R5A1_UNORM_PACK16", "A1R5G5B5_UNORM_PACK16", "R8_UNORM", "R8_SNORM", "R8_USCALED", "R8_SSCALED", "R8_UINT", "R8_SINT", "R8_SRGB", "R8G8_UNORM", "R8G8_SNORM", "R8G8_USCALED", "R8G8_SSCALED", "R8G8_UINT", "R8G8_SINT", "R8G8_SRGB", "R8G8B8_UNORM", "R8G8B8_SNORM", "R8G8B8_USCALED", "R8G8B8_SSCALED", "R8G8B8_UINT", "R8G8B8_SINT", "R8G8B8_SRGB", "B8G8R8_UNORM", "B8G8R8_SNORM", "B8G8R8_USCALED", "B8G8R8_SSCALED", "B8G8R8_UINT", "B8G8R8_SINT", "B8G8R8_SRGB", "R8G8B8A8_UNORM", "R8G8B8A8_SNORM", "R8G8B8A8_USCALED", "R8G8B8A8_SSCALED", "R8G8B8A8_UINT", "R8G8B8A8_SINT", "R8G8B8A8_SRGB", "B8G8R8A8_UNORM", "B8G8R8A8_SNORM", "B8G8R8A8_USCALED", "B8G8R8A8_SSCALED", "B8G8R8A8_UINT", "B8G8R8A8_SINT", "B8G8R8A8_SRGB", "A8B8G8R8_UNORM_PACK32", "A8B8G8R8_SNORM_PACK32", "A8B8G8R8_USCALED_PACK32", "A8B8G8R8_SSCALED_PACK32", "A8B8G8R8_UINT_PACK32", "A8B8G8R8_SINT_PACK32", "A8B8G8R8_SRGB_PACK32", "A2R10G10B10_UNORM_PACK32", "A2R10G10B10_SNORM_PACK32", "A2R10G10B10_USCALED_PACK32", "A2R10G10B10_SSCALED_PACK32", "A2R10G10B10_UINT_PACK32", "A2R10G10B10_SINT_PACK32", "A2B10G10R10_UNORM_PACK32", "A2B10G10R10_SNORM_PACK32", "A2B10G10R10_USCALED_PACK32", "A2B10G10R10_SSCALED_PACK32", "A2B10G10R10_UINT_PACK32", "A2B10G10R10_SINT_PACK32", "R16_UNORM", "R16_SNORM", "R16_USCALED", "R16_SSCALED", "R16_UINT", "R16_SINT", "R16_SFLOAT", "R16G16_UNORM", "R16G16_SNORM", "R16G16_USCALED", "R16G16_SSCALED", "R16G16_UINT", "R16G16_SINT", "R16G16_SFLOAT", "R16G16B16_UNORM", "R16G16B16_SNORM", "R16G16B16_USCALED", "R16G16B16_SSCALED", "R16G16B16_UINT", "R16G16B16_SINT", "R16G16B16_SFLOAT", "R16G16B16A16_UNORM", "R16G16B16A16_SNORM", "R16G16B16A16_USCALED", "R16G16B16A16_SSCALED", "R16G16B16A16_UINT", "R16G16B16A16_SINT", "R16G16B16A16_SFLOAT", "R32_UINT", "R32_SINT", "R32_SFLOAT", "R32G32_UINT", "R32G32_SINT", "R32G32_SFLOAT", "R32G32B32_UINT", "R32G32B32_SINT", "R32G32B32_SFLOAT", "R32G32B32A32_UINT", "R32G32B32A32_SINT", "R32G32B32A32_SFLOAT", "R64_UINT", "R64_SINT", "R64_SFLOAT", "R64G64_UINT", "R64G64_SINT", "R64G64_SFLOAT", "R64G64B64_UINT", "R64G64B64_SINT", "R64G64B64_SFLOAT", "R64G64B64A64_UINT", "R64G64B64A64_SINT", "R64G64B64A64_SFLOAT", "B10G11R11_UFLOAT_PACK32", "E5B9G9R9_UFLOAT_PACK32", "D16_UNORM", "X8_D24_UNORM_PACK32", "D32_SFLOAT", "S8_UINT", "D16_UNORM_S8_UINT", "D24_UNORM_S8_UINT", "D32_SFLOAT_S8_UINT", "BC1_RGB_UNORM_BLOCK", "BC1_RGB_SRGB_BLOCK", "BC1_RGBA_UNORM_BLOCK", "BC1_RGBA_SRGB_BLOCK", "BC2_UNORM_BLOCK", "BC2_SRGB_BLOCK", "BC3_UNORM_BLOCK", "BC3_SRGB_BLOCK", "BC4_UNORM_BLOCK", "BC4_SNORM_BLOCK", "BC5_UNORM_BLOCK", "BC5_SNORM_BLOCK", "BC6H_UFLOAT_BLOCK", "BC6H_SFLOAT_BLOCK", "BC7_UNORM_BLOCK", "BC7_SRGB_BLOCK", "ETC2_R8G8B8_UNORM_BLOCK", "ETC2_R8G8B8_SRGB_BLOCK", "ETC2_R8G8B8A1_UNORM_BLOCK", "ETC2_R8G8B8A1_SRGB_BLOCK", "ETC2_R8G8B8A8_UNORM_BLOCK", "ETC2_R8G8B8A8_SRGB_BLOCK", "EAC_R11_UNORM_BLOCK", "EAC_R11_SNORM_BLOCK", "EAC_R11G11_UNORM_BLOCK", "EAC_R11G11_SNORM_BLOCK", "ASTC_4x4_UNORM_BLOCK", "ASTC_4x4_SRGB_BLOCK", "ASTC_5x4_UNORM_BLOCK", "ASTC_5x4_SRGB_BLOCK", "ASTC_5x5_UNORM_BLOCK", "ASTC_5x5_SRGB_BLOCK", "ASTC_6x5_UNORM_BLOCK", "ASTC_6x5_SRGB_BLOCK", "ASTC_6x6_UNORM_BLOCK", "ASTC_6x6_SRGB_BLOCK", "ASTC_8x5_UNORM_BLOCK", "ASTC_8x5_SRGB_BLOCK", "ASTC_8x6_UNORM_BLOCK", "ASTC_8x6_SRGB_BLOCK", "ASTC_8x8_UNORM_BLOCK", "ASTC_8x8_SRGB_BLOCK", "ASTC_10x5_UNORM_BLOCK", "ASTC_10x5_SRGB_BLOCK", "ASTC_10x6_UNORM_BLOCK", "ASTC_10x6_SRGB_BLOCK", "ASTC_10x8_UNORM_BLOCK", "ASTC_10x8_SRGB_BLOCK", "ASTC_10x10_UNORM_BLOCK", "ASTC_10x10_SRGB_BLOCK", "ASTC_12x10_UNORM_BLOCK", "ASTC_12x10_SRGB_BLOCK", "ASTC_12x12_UNORM_BLOCK", "ASTC_12x12_SRGB_BLOCK" };
	if (format < VK_FORMAT_RANGE_SIZE)
	{
		return knownFormats[format];
	}
	switch (format)
	{
		case VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG:
			return "PVRTC1_2BPP_UNORM_BLOCK_IMG";
		case VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG:
			return "PVRTC1_4BPP_UNORM_BLOCK_IMG";
		case VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG:
			return "PVRTC2_2BPP_UNORM_BLOCK_IMG";
		case VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG:
			return "PVRTC2_4BPP_UNORM_BLOCK_IMG";
		case VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG:
			return "PVRTC1_2BPP_SRGB_BLOCK_IMG";
		case VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG:
			return "PVRTC1_4BPP_SRGB_BLOCK_IMG";
		case VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG:
			return "PVRTC2_2BPP_SRGB_BLOCK_IMG";
		case VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG:
			return "PVRTC2_4BPP_SRGB_BLOCK_IMG";
		case VK_FORMAT_MAX_ENUM:
			return "MAX_ENUM";
		default:
			return "UNKNOWN";
	}
}